// Long-form FAQ content. Kept out of i18n.ts on purpose: these are paragraphs,
// not UI labels, and inlining them would bloat every language dictionary.
// {fee} and {net} are substituted at render time with the live platform fee.

export interface QA { q: string; a: string; }

const en: QA[] = [
  { q: 'What are connects and why do I need them?',
    a: 'Connects are the internal activity currency. Posting a job costs 1 connect; applying costs 1 connect per 50π of budget (minimum 1). Connects are not returned if your application is declined or the job is deleted. You can buy them with Pi in your profile.' },
  { q: 'How does escrow work?',
    a: 'When a client hires a freelancer, the job budget is paid in Pi and locked in escrow. The freelancer can work knowing payment is secured. Once the work is accepted, the client taps “Release all” and the funds go to the freelancer.' },
  { q: 'What is the platform fee?',
    a: 'The platform keeps {fee}% of the freelancer payout. Example: a 10π budget → the client pays 10π and the freelancer receives {net}π.' },
  { q: 'How do I get paid to my Pi wallet?',
    a: 'Payouts arrive as real Pi in your Pi Wallet automatically when escrow is released. Important: you must have a Pi wallet created, and you must allow access to your wallet address when signing in. If you had no wallet, create one in Pi Browser and sign in to Work Pro again.' },
  { q: 'How are “Applied” and “Offers” different?',
    a: '“Applied” are the applications YOU sent to other people’s jobs. “Offers” are jobs a client sent directly to YOU — accept or decline them under My Jobs → Offers.' },
  { q: 'What is the portfolio?',
    a: 'A showcase of your work on your profile. Clients look at it when choosing who to hire, so add your best projects with a short description.' },
  { q: 'What if I am not happy with the work?',
    a: 'Do not release the escrow. Open a “Dispute” on the Escrow page and an administrator will review it and decide whether to pay the freelancer or refund you. You can also tap “Cancel” for a refund while the work has not been submitted.' },
  { q: 'What if the client disappears and never accepts the work?',
    a: 'If you submitted the work and the client does not respond for 14 days, the escrow is released to you automatically.' },
  { q: 'Are payments real Pi?',
    a: 'Yes. Work Pro runs on Pi Mainnet, so every payment is real Pi. Funds are held in escrow until the work is accepted.' },
  { q: 'How do I delete my job?',
    a: 'An open job can be deleted from the job page. A job already in progress cannot be — finish it or cancel the escrow first.' },
];

const ru: QA[] = [
  { q: 'Что такое коннекты и зачем они нужны?',
    a: 'Коннекты — внутренняя валюта активности. Публикация задачи стоит 1 коннект, отклик — 1 коннект за каждые 50π бюджета (минимум 1). Коннекты не возвращаются при отклонении отклика или удалении задачи. Купить их можно за Pi в профиле.' },
  { q: 'Как работает эскроу?',
    a: 'При найме фрилансера заказчик оплачивает бюджет задачи через Pi — деньги замораживаются в эскроу. Фрилансер спокойно работает: оплата гарантирована. После приёмки работы заказчик нажимает «Выплатить всё», и деньги уходят фрилансеру.' },
  { q: 'Какая комиссия платформы?',
    a: 'Платформа удерживает {fee}% из выплаты фрилансеру. Пример: бюджет 10π → заказчик платит 10π, фрилансер получает {net}π.' },
  { q: 'Как получить выплату на Pi-кошелёк?',
    a: 'Выплаты приходят реальными Pi на ваш Pi Wallet автоматически при выплате эскроу. Важно: у вас должен быть создан Pi-кошелёк, и при входе в приложение нужно разрешить доступ к адресу кошелька. Если кошелька не было — создайте его в Pi Browser и перезайдите в Work Pro.' },
  { q: 'Чем «Отклики» отличаются от «Предложений»?',
    a: '«Отклики» — заявки, которые ВЫ отправили на чужие задачи. «Предложения» — когда заказчик сам предлагает задачу ВАМ напрямую; их можно принять или отклонить в разделе «Мои работы → Предложения».' },
  { q: 'Что такое портфолио?',
    a: 'Витрина ваших работ в профиле — заказчики видят её при выборе исполнителя. Добавляйте лучшие проекты с описанием.' },
  { q: 'Что делать, если работа не устраивает?',
    a: 'Не выплачивайте эскроу. Откройте «Спор» на странице Эскроу — администратор рассмотрит и решит: выплатить фрилансеру или вернуть вам. Либо нажмите «Отмена» для возврата средств, пока работа не сдана.' },
  { q: 'Что будет, если заказчик пропал и не принимает работу?',
    a: 'Если вы сдали работу, а заказчик 14 дней не реагирует — эскроу выплачивается вам автоматически.' },
  { q: 'Платежи — это настоящие Pi?',
    a: 'Да. Work Pro работает в основной сети Pi (Mainnet), поэтому все платежи — настоящие Pi. Средства удерживаются в эскроу, пока работа не принята.' },
  { q: 'Как удалить свою задачу?',
    a: 'Открытую задачу можно удалить со страницы задачи. Задачу в работе удалить нельзя — сначала завершите её или отмените эскроу.' },
];

const uk: QA[] = [
  { q: 'Що таке конекти і навіщо вони?',
    a: 'Конекти — внутрішня валюта активності. Публікація задачі коштує 1 конект, відгук — 1 конект за кожні 50π бюджету (мінімум 1). Конекти не повертаються, якщо відгук відхилено або задачу видалено. Придбати їх можна за Pi у профілі.' },
  { q: 'Як працює ескроу?',
    a: 'Наймаючи фрилансера, замовник оплачує бюджет задачі в Pi — кошти заморожуються в ескроу. Фрилансер працює спокійно: оплата гарантована. Після приймання роботи замовник тисне «Виплатити все», і гроші йдуть фрилансеру.' },
  { q: 'Яка комісія платформи?',
    a: 'Платформа утримує {fee}% з виплати фрилансеру. Приклад: бюджет 10π → замовник платить 10π, фрилансер отримує {net}π.' },
  { q: 'Як отримати виплату на Pi-гаманець?',
    a: 'Виплати надходять справжніми Pi на ваш Pi Wallet автоматично при виплаті ескроу. Важливо: гаманець має бути створений, і під час входу треба дозволити доступ до адреси гаманця. Якщо гаманця не було — створіть його в Pi Browser і зайдіть у Work Pro знову.' },
  { q: 'Чим «Відгуки» відрізняються від «Пропозицій»?',
    a: '«Відгуки» — заявки, які ВИ надіслали на чужі задачі. «Пропозиції» — коли замовник пропонує задачу ВАМ напряму; їх можна прийняти або відхилити в розділі «Мої роботи → Пропозиції».' },
  { q: 'Що таке портфоліо?',
    a: 'Вітрина ваших робіт у профілі — замовники бачать її при виборі виконавця. Додавайте найкращі проєкти з описом.' },
  { q: 'Що робити, якщо робота не влаштовує?',
    a: 'Не виплачуйте ескроу. Відкрийте «Спір» на сторінці Ескроу — адміністратор розгляне і вирішить: виплатити фрилансеру чи повернути вам. Або натисніть «Скасувати» для повернення коштів, поки роботу не здано.' },
  { q: 'Що буде, якщо замовник зник і не приймає роботу?',
    a: 'Якщо ви здали роботу, а замовник 14 днів не реагує — ескроу виплачується вам автоматично.' },
  { q: 'Платежі — це справжні Pi?',
    a: 'Так. Work Pro працює в основній мережі Pi (Mainnet), тому всі платежі — справжні Pi. Кошти утримуються в ескроу, поки роботу не прийнято.' },
  { q: 'Як видалити свою задачу?',
    a: 'Відкриту задачу можна видалити зі сторінки задачі. Задачу в роботі видалити не можна — спершу завершіть її або скасуйте ескроу.' },
];

const de: QA[] = [
  { q: 'Was sind Connects und wofür brauche ich sie?',
    a: 'Connects sind die interne Aktivitätswährung. Einen Auftrag einzustellen kostet 1 Connect, eine Bewerbung 1 Connect je 50π Budget (mindestens 1). Connects werden nicht erstattet, wenn deine Bewerbung abgelehnt oder der Auftrag gelöscht wird. Du kannst sie im Profil mit Pi kaufen.' },
  { q: 'Wie funktioniert das Treuhandkonto?',
    a: 'Beim Beauftragen zahlt der Kunde das Budget in Pi — das Geld wird im Treuhandkonto gesperrt. Der Freelancer arbeitet mit gesicherter Bezahlung. Nach Abnahme tippt der Kunde auf „Alles auszahlen“ und das Geld geht an den Freelancer.' },
  { q: 'Wie hoch ist die Plattformgebühr?',
    a: 'Die Plattform behält {fee}% der Freelancer-Auszahlung ein. Beispiel: 10π Budget → der Kunde zahlt 10π, der Freelancer erhält {net}π.' },
  { q: 'Wie werde ich auf meine Pi-Wallet bezahlt?',
    a: 'Auszahlungen kommen als echte Pi automatisch in deiner Pi Wallet an, sobald das Treuhandkonto freigegeben wird. Wichtig: Du brauchst eine angelegte Pi-Wallet und musst beim Anmelden den Zugriff auf deine Wallet-Adresse erlauben. Ohne Wallet: im Pi Browser eine anlegen und dich erneut bei Work Pro anmelden.' },
  { q: 'Was ist der Unterschied zwischen „Beworben“ und „Angebote“?',
    a: '„Beworben“ sind Bewerbungen, die DU auf fremde Aufträge geschickt hast. „Angebote“ sind Aufträge, die ein Kunde DIR direkt geschickt hat — annehmen oder ablehnen unter Meine Jobs → Angebote.' },
  { q: 'Was ist das Portfolio?',
    a: 'Eine Schaufenster deiner Arbeiten im Profil. Kunden sehen es bei der Auswahl — füge deine besten Projekte mit kurzer Beschreibung hinzu.' },
  { q: 'Was, wenn mir die Arbeit nicht gefällt?',
    a: 'Gib das Treuhandkonto nicht frei. Öffne auf der Escrow-Seite einen „Streitfall“ — ein Administrator prüft und entscheidet, ob ausgezahlt oder erstattet wird. Solange nichts abgegeben wurde, kannst du auch „Abbrechen“ für eine Rückerstattung tippen.' },
  { q: 'Was, wenn der Kunde verschwindet und nie abnimmt?',
    a: 'Hast du die Arbeit abgegeben und der Kunde reagiert 14 Tage nicht, wird das Treuhandkonto automatisch an dich ausgezahlt.' },
  { q: 'Sind die Zahlungen echte Pi?',
    a: 'Ja. Work Pro läuft im Pi-Mainnet, alle Zahlungen sind also echte Pi. Das Geld bleibt treuhänderisch hinterlegt, bis die Arbeit abgenommen ist.' },
  { q: 'Wie lösche ich meinen Auftrag?',
    a: 'Einen offenen Auftrag kannst du auf der Auftragsseite löschen. Einen laufenden nicht — schließe ihn zuerst ab oder storniere das Treuhandkonto.' },
];

const fr: QA[] = [
  { q: 'Que sont les connects et à quoi servent-ils ?',
    a: 'Les connects sont la monnaie d’activité interne. Publier une mission coûte 1 connect, postuler coûte 1 connect par tranche de 50π de budget (minimum 1). Les connects ne sont pas rendus si votre candidature est refusée ou la mission supprimée. Achetez-en avec des Pi depuis votre profil.' },
  { q: 'Comment fonctionne le séquestre ?',
    a: 'À l’embauche, le client paie le budget en Pi — les fonds sont bloqués en séquestre. Le freelance travaille avec un paiement garanti. Après acceptation, le client appuie sur « Tout verser » et les fonds partent au freelance.' },
  { q: 'Quelle est la commission de la plateforme ?',
    a: 'La plateforme retient {fee}% du versement au freelance. Exemple : budget de 10π → le client paie 10π et le freelance reçoit {net}π.' },
  { q: 'Comment être payé sur mon portefeuille Pi ?',
    a: 'Les versements arrivent en Pi réels sur votre Pi Wallet automatiquement à la libération du séquestre. Important : vous devez avoir créé un portefeuille Pi et autoriser l’accès à son adresse à la connexion. Sans portefeuille, créez-en un dans Pi Browser puis reconnectez-vous à Work Pro.' },
  { q: 'Quelle différence entre « Candidatures » et « Offres » ?',
    a: '« Candidatures » : les demandes que VOUS avez envoyées sur les missions des autres. « Offres » : les missions qu’un client VOUS a envoyées directement — à accepter ou refuser dans Mes missions → Offres.' },
  { q: 'Qu’est-ce que le portfolio ?',
    a: 'Une vitrine de vos réalisations sur votre profil. Les clients la consultent avant de recruter : ajoutez vos meilleurs projets avec une courte description.' },
  { q: 'Que faire si le travail ne convient pas ?',
    a: 'Ne libérez pas le séquestre. Ouvrez un « Litige » sur la page Séquestre : un administrateur examinera et décidera de payer le freelance ou de vous rembourser. Tant que rien n’est livré, vous pouvez aussi appuyer sur « Annuler » pour être remboursé.' },
  { q: 'Et si le client disparaît sans accepter le travail ?',
    a: 'Si vous avez livré et que le client ne répond pas pendant 14 jours, le séquestre vous est versé automatiquement.' },
  { q: 'Les paiements sont-ils en vrais Pi ?',
    a: 'Oui. Work Pro fonctionne sur le Mainnet de Pi : tous les paiements sont en vrais Pi. Les fonds restent sous séquestre jusqu’à l’acceptation du travail.' },
  { q: 'Comment supprimer ma mission ?',
    a: 'Une mission ouverte se supprime depuis sa page. Une mission en cours ne peut pas l’être — terminez-la ou annulez le séquestre d’abord.' },
];

const es: QA[] = [
  { q: '¿Qué son los connects y para qué sirven?',
    a: 'Los connects son la moneda interna de actividad. Publicar un encargo cuesta 1 connect; postularse cuesta 1 connect por cada 50π de presupuesto (mínimo 1). No se devuelven si rechazan tu postulación o borran el encargo. Puedes comprarlos con Pi en tu perfil.' },
  { q: '¿Cómo funciona el depósito en garantía?',
    a: 'Al contratar, el cliente paga el presupuesto en Pi y los fondos quedan bloqueados en depósito. El freelancer trabaja con el pago asegurado. Tras aceptar el trabajo, el cliente pulsa «Liberar todo» y el dinero pasa al freelancer.' },
  { q: '¿Cuál es la comisión de la plataforma?',
    a: 'La plataforma retiene el {fee}% del pago al freelancer. Ejemplo: presupuesto de 10π → el cliente paga 10π y el freelancer recibe {net}π.' },
  { q: '¿Cómo cobro en mi monedero Pi?',
    a: 'Los pagos llegan como Pi reales a tu Pi Wallet automáticamente al liberar el depósito. Importante: debes tener un monedero Pi creado y permitir el acceso a su dirección al iniciar sesión. Si no lo tenías, créalo en Pi Browser y vuelve a entrar en Work Pro.' },
  { q: '¿En qué se diferencian «Postulaciones» y «Ofertas»?',
    a: '«Postulaciones» son las solicitudes que TÚ enviaste a encargos de otros. «Ofertas» son encargos que un cliente TE envió directamente: acéptalas o recházalas en Mis trabajos → Ofertas.' },
  { q: '¿Qué es el portafolio?',
    a: 'Un escaparate de tus trabajos en el perfil. Los clientes lo miran al elegir a quién contratar, así que añade tus mejores proyectos con una breve descripción.' },
  { q: '¿Qué hago si el trabajo no me convence?',
    a: 'No liberes el depósito. Abre una «Disputa» en la página de Depósito: un administrador la revisará y decidirá si paga al freelancer o te reembolsa. Mientras no se haya entregado, también puedes pulsar «Cancelar» para recuperar el dinero.' },
  { q: '¿Y si el cliente desaparece y no acepta el trabajo?',
    a: 'Si entregaste el trabajo y el cliente no responde en 14 días, el depósito se te libera automáticamente.' },
  { q: '¿Los pagos son Pi reales?',
    a: 'Sí. Work Pro funciona en la Mainnet de Pi, así que todos los pagos son Pi reales. Los fondos quedan en depósito hasta que se acepta el trabajo.' },
  { q: '¿Cómo elimino mi encargo?',
    a: 'Un encargo abierto se elimina desde su página. Uno en curso no — termínalo o cancela el depósito primero.' },
];

const pt: QA[] = [
  { q: 'O que são connects e para que servem?',
    a: 'Connects são a moeda interna de atividade. Publicar uma tarefa custa 1 connect; candidatar-se custa 1 connect a cada 50π de orçamento (mínimo 1). Não são devolvidos se a candidatura for recusada ou a tarefa apagada. Compre-os com Pi no seu perfil.' },
  { q: 'Como funciona a custódia?',
    a: 'Ao contratar, o cliente paga o orçamento em Pi e os fundos ficam bloqueados em custódia. O freelancer trabalha com pagamento garantido. Após aceitar o trabalho, o cliente toca em “Liberar tudo” e o dinheiro vai para o freelancer.' },
  { q: 'Qual é a taxa da plataforma?',
    a: 'A plataforma retém {fee}% do pagamento ao freelancer. Exemplo: orçamento de 10π → o cliente paga 10π e o freelancer recebe {net}π.' },
  { q: 'Como recebo na minha carteira Pi?',
    a: 'Os pagamentos chegam como Pi reais na sua Pi Wallet automaticamente quando a custódia é liberada. Importante: você precisa ter uma carteira Pi criada e permitir o acesso ao endereço dela ao entrar. Se não tinha carteira, crie uma no Pi Browser e entre no Work Pro novamente.' },
  { q: 'Qual a diferença entre “Candidaturas” e “Ofertas”?',
    a: '“Candidaturas” são os pedidos que VOCÊ enviou para tarefas de outros. “Ofertas” são tarefas que um cliente enviou diretamente para VOCÊ — aceite ou recuse em Meus trabalhos → Ofertas.' },
  { q: 'O que é o portfólio?',
    a: 'Uma vitrine dos seus trabalhos no perfil. Os clientes olham para ela ao escolher quem contratar, então adicione seus melhores projetos com uma breve descrição.' },
  { q: 'E se eu não gostar do trabalho?',
    a: 'Não libere a custódia. Abra uma “Disputa” na página de Custódia: um administrador vai analisar e decidir entre pagar o freelancer ou reembolsar você. Enquanto nada foi entregue, você também pode tocar em “Cancelar” para reembolso.' },
  { q: 'E se o cliente sumir e nunca aceitar o trabalho?',
    a: 'Se você entregou o trabalho e o cliente não responde por 14 dias, a custódia é liberada para você automaticamente.' },
  { q: 'Os pagamentos são Pi reais?',
    a: 'Sim. O Work Pro roda na Mainnet da Pi, portanto todos os pagamentos são Pi reais. Os fundos ficam em custódia até o trabalho ser aceito.' },
  { q: 'Como excluo minha tarefa?',
    a: 'Uma tarefa aberta pode ser excluída na página dela. Uma em andamento não — conclua-a ou cancele a custódia primeiro.' },
];

const it: QA[] = [
  { q: 'Cosa sono i connect e a cosa servono?',
    a: 'I connect sono la valuta interna di attività. Pubblicare un incarico costa 1 connect; candidarsi costa 1 connect ogni 50π di budget (minimo 1). Non vengono restituiti se la candidatura viene rifiutata o l’incarico eliminato. Puoi acquistarli con Pi dal profilo.' },
  { q: 'Come funziona il deposito a garanzia?',
    a: 'All’assunzione il cliente paga il budget in Pi e i fondi restano bloccati in deposito. Il freelance lavora con il pagamento garantito. Dopo l’accettazione il cliente tocca “Rilascia tutto” e il denaro va al freelance.' },
  { q: 'Qual è la commissione della piattaforma?',
    a: 'La piattaforma trattiene il {fee}% del pagamento al freelance. Esempio: budget di 10π → il cliente paga 10π e il freelance riceve {net}π.' },
  { q: 'Come ricevo il pagamento sul mio wallet Pi?',
    a: 'I pagamenti arrivano come Pi reali sul tuo Pi Wallet automaticamente al rilascio del deposito. Importante: devi avere un wallet Pi creato e consentire l’accesso al suo indirizzo all’accesso. Se non ne avevi uno, crealo in Pi Browser e rientra in Work Pro.' },
  { q: 'Che differenza c’è tra “Candidature” e “Offerte”?',
    a: '“Candidature” sono le richieste che TU hai inviato agli incarichi altrui. “Offerte” sono incarichi che un cliente ha inviato direttamente a TE — accettale o rifiutale in I miei lavori → Offerte.' },
  { q: 'Cos’è il portfolio?',
    a: 'Una vetrina dei tuoi lavori sul profilo. I clienti la guardano quando scelgono chi assumere: aggiungi i progetti migliori con una breve descrizione.' },
  { q: 'Cosa faccio se il lavoro non mi soddisfa?',
    a: 'Non rilasciare il deposito. Apri una “Controversia” nella pagina Deposito: un amministratore esaminerà e deciderà se pagare il freelance o rimborsarti. Finché nulla è stato consegnato puoi anche toccare “Annulla” per il rimborso.' },
  { q: 'E se il cliente sparisce e non accetta il lavoro?',
    a: 'Se hai consegnato il lavoro e il cliente non risponde per 14 giorni, il deposito viene rilasciato automaticamente a te.' },
  { q: 'I pagamenti sono in Pi reali?',
    a: 'Sì. Work Pro gira sulla Mainnet di Pi, quindi tutti i pagamenti sono in Pi reali. I fondi restano in deposito finché il lavoro non viene accettato.' },
  { q: 'Come elimino il mio incarico?',
    a: 'Un incarico aperto si elimina dalla sua pagina. Uno già in corso no — completalo o annulla prima il deposito.' },
];

const tr_: QA[] = [
  { q: 'Connect nedir, ne işe yarar?',
    a: 'Connect, uygulamanın iç etkinlik birimidir. İş ilanı vermek 1 connect, başvurmak her 50π bütçe için 1 connect (en az 1) tutar. Başvurunuz reddedilirse ya da ilan silinirse connectler iade edilmez. Profilinizden Pi ile satın alabilirsiniz.' },
  { q: 'Emanet (escrow) nasıl çalışır?',
    a: 'İşveren birini işe alırken bütçeyi Pi ile öder ve para emanette kilitlenir. Serbest çalışan, ödemesi güvencede olarak çalışır. İş kabul edildikten sonra işveren “Tümünü serbest bırak” der ve para serbest çalışana geçer.' },
  { q: 'Platform komisyonu ne kadar?',
    a: 'Platform, serbest çalışana yapılan ödemenin %{fee} kadarını alır. Örnek: 10π bütçe → işveren 10π öder, serbest çalışan {net}π alır.' },
  { q: 'Pi cüzdanıma ödeme nasıl gelir?',
    a: 'Emanet serbest bırakıldığında ödemeler gerçek Pi olarak Pi Wallet’ınıza otomatik gelir. Önemli: oluşturulmuş bir Pi cüzdanınız olmalı ve girişte cüzdan adresinize erişime izin vermelisiniz. Cüzdanınız yoksa Pi Browser’da oluşturup Work Pro’ya yeniden girin.' },
  { q: '“Başvurular” ile “Teklifler” farkı ne?',
    a: '“Başvurular”, SİZİN başkalarının ilanlarına gönderdiğiniz taleplerdir. “Teklifler” ise bir işverenin doğrudan SİZE gönderdiği işlerdir — İşlerim → Teklifler’den kabul edin ya da reddedin.' },
  { q: 'Portföy nedir?',
    a: 'Profilinizdeki çalışma vitrininiz. İşverenler kimi işe alacağına karar verirken buraya bakar; en iyi projelerinizi kısa açıklamayla ekleyin.' },
  { q: 'İşten memnun kalmazsam ne olur?',
    a: 'Emaneti serbest bırakmayın. Emanet sayfasından “Anlaşmazlık” açın; bir yönetici inceleyip serbest çalışana ödeme mi yapılacağına yoksa size iade mi edileceğine karar verir. Teslim yapılmadıysa “İptal” ile iade de alabilirsiniz.' },
  { q: 'İşveren kaybolur ve işi kabul etmezse?',
    a: 'İşi teslim ettiyseniz ve işveren 14 gün yanıt vermezse, emanet otomatik olarak size ödenir.' },
  { q: 'Ödemeler gerçek Pi mi?',
    a: 'Evet. Work Pro Pi Mainnet üzerinde çalışır, bu yüzden tüm ödemeler gerçek Pi’dir. Para, iş kabul edilene kadar emanette tutulur.' },
  { q: 'İlanımı nasıl silerim?',
    a: 'Açık bir ilanı kendi sayfasından silebilirsiniz. Devam eden bir işi silemezsiniz — önce tamamlayın ya da emaneti iptal edin.' },
];

const pl: QA[] = [
  { q: 'Czym są connecty i po co są?',
    a: 'Connecty to wewnętrzna waluta aktywności. Opublikowanie zlecenia kosztuje 1 connect, zgłoszenie — 1 connect za każde 50π budżetu (minimum 1). Connecty nie wracają, gdy zgłoszenie zostanie odrzucone lub zlecenie usunięte. Kupisz je za Pi w profilu.' },
  { q: 'Jak działa depozyt (escrow)?',
    a: 'Przy zatrudnieniu klient płaci budżet w Pi — środki zostają zablokowane w depozycie. Freelancer pracuje z gwarantowaną zapłatą. Po odbiorze klient klika „Wypłać wszystko” i pieniądze trafiają do freelancera.' },
  { q: 'Jaka jest prowizja platformy?',
    a: 'Platforma potrąca {fee}% z wypłaty dla freelancera. Przykład: budżet 10π → klient płaci 10π, freelancer dostaje {net}π.' },
  { q: 'Jak otrzymać wypłatę na portfel Pi?',
    a: 'Wypłaty trafiają jako prawdziwe Pi do twojego Pi Wallet automatycznie po zwolnieniu depozytu. Ważne: musisz mieć utworzony portfel Pi i przy logowaniu zezwolić na dostęp do jego adresu. Jeśli portfela nie było — utwórz go w Pi Browser i zaloguj się ponownie do Work Pro.' },
  { q: 'Czym różnią się „Zgłoszenia” od „Ofert”?',
    a: '„Zgłoszenia” to wnioski, które TY wysłałeś na cudze zlecenia. „Oferty” to zlecenia wysłane przez klienta bezpośrednio DO CIEBIE — przyjmij je lub odrzuć w Moje zlecenia → Oferty.' },
  { q: 'Czym jest portfolio?',
    a: 'Witryna twoich prac w profilu. Klienci oglądają ją przy wyborze wykonawcy — dodaj najlepsze projekty z krótkim opisem.' },
  { q: 'Co zrobić, gdy praca nie odpowiada?',
    a: 'Nie zwalniaj depozytu. Otwórz „Spór” na stronie Depozytu — administrator rozpatrzy i zdecyduje: zapłacić freelancerowi czy zwrócić tobie. Dopóki nic nie oddano, możesz też kliknąć „Anuluj” i odzyskać środki.' },
  { q: 'Co, jeśli klient zniknie i nie odbierze pracy?',
    a: 'Jeśli oddałeś pracę, a klient nie reaguje przez 14 dni — depozyt zostanie wypłacony tobie automatycznie.' },
  { q: 'Czy płatności to prawdziwe Pi?',
    a: 'Tak. Work Pro działa w sieci głównej Pi (Mainnet), więc wszystkie płatności to prawdziwe Pi. Środki są w depozycie, dopóki praca nie zostanie przyjęta.' },
  { q: 'Jak usunąć swoje zlecenie?',
    a: 'Otwarte zlecenie usuniesz z jego strony. Zlecenia w toku nie da się usunąć — najpierw je zakończ lub anuluj depozyt.' },
];

const ar: QA[] = [
  { q: 'ما هي نقاط التواصل ولماذا أحتاجها؟',
    a: 'نقاط التواصل هي عملة النشاط داخل التطبيق. نشر وظيفة يكلّف نقطة واحدة، والتقدّم يكلّف نقطة لكل 50π من الميزانية (بحد أدنى نقطة). لا تُسترد النقاط إذا رُفض طلبك أو حُذفت الوظيفة. يمكنك شراؤها بعملة Pi من ملفك الشخصي.' },
  { q: 'كيف يعمل الضمان؟',
    a: 'عند التوظيف يدفع العميل الميزانية بعملة Pi فتُجمَّد في الضمان. يعمل المستقل والدفع مضمون. بعد قبول العمل يضغط العميل «تحرير الكل» فتُحوَّل الأموال إلى المستقل.' },
  { q: 'كم عمولة المنصة؟',
    a: 'تحتفظ المنصة بنسبة {fee}% من مستحقات المستقل. مثال: ميزانية 10π ← يدفع العميل 10π ويستلم المستقل {net}π.' },
  { q: 'كيف أستلم الدفع في محفظة Pi؟',
    a: 'تصل المدفوعات بعملة Pi حقيقية إلى محفظتك تلقائيًا عند تحرير الضمان. مهم: يجب أن تكون لديك محفظة Pi منشأة، وأن تسمح بالوصول إلى عنوانها عند تسجيل الدخول. إن لم تكن لديك محفظة، أنشئها في Pi Browser ثم ادخل Work Pro من جديد.' },
  { q: 'ما الفرق بين «الطلبات» و«العروض»؟',
    a: '«الطلبات» هي ما أرسلتَه أنت إلى وظائف الآخرين. «العروض» هي وظائف أرسلها عميل إليك مباشرة — اقبلها أو ارفضها من «وظائفي ← العروض».' },
  { q: 'ما هو المعرض (البورتفوليو)؟',
    a: 'واجهة لأعمالك في ملفك الشخصي. ينظر إليها العملاء عند اختيار من يوظّفون، فأضف أفضل مشاريعك مع وصف قصير.' },
  { q: 'ماذا أفعل إذا لم يعجبني العمل؟',
    a: 'لا تحرّر الضمان. افتح «نزاعًا» من صفحة الضمان وسيراجعه المشرف ويقرر: الدفع للمستقل أم إعادة المبلغ إليك. وما دام لم يُسلَّم شيء يمكنك الضغط على «إلغاء» لاسترداد أموالك.' },
  { q: 'ماذا لو اختفى العميل ولم يقبل العمل؟',
    a: 'إذا سلّمتَ العمل ولم يستجب العميل خلال 14 يومًا، يُحرَّر الضمان لك تلقائيًا.' },
  { q: 'هل المدفوعات بعملة Pi حقيقية؟',
    a: 'نعم. يعمل Work Pro على شبكة Pi الرئيسية (Mainnet)، لذا كل المدفوعات بعملة Pi حقيقية. تبقى الأموال في الضمان حتى قبول العمل.' },
  { q: 'كيف أحذف وظيفتي؟',
    a: 'يمكن حذف الوظيفة المفتوحة من صفحتها. أما الوظيفة الجارية فلا يمكن حذفها — أنهِها أولًا أو ألغِ الضمان.' },
];

const hi: QA[] = [
  { q: 'कनेक्ट्स क्या हैं और क्यों चाहिए?',
    a: 'कनेक्ट्स ऐप की आंतरिक गतिविधि मुद्रा हैं। काम पोस्ट करने पर 1 कनेक्ट लगता है, आवेदन पर हर 50π बजट के लिए 1 कनेक्ट (कम से कम 1)। आवेदन अस्वीकृत होने या काम हटने पर कनेक्ट्स वापस नहीं मिलते। इन्हें प्रोफ़ाइल में Pi से खरीदा जा सकता है।' },
  { q: 'एस्क्रो कैसे काम करता है?',
    a: 'नियुक्ति के समय क्लाइंट बजट Pi में चुकाता है और राशि एस्क्रो में लॉक हो जाती है। फ्रीलांसर निश्चिंत होकर काम करता है — भुगतान सुरक्षित है। काम स्वीकार होने पर क्लाइंट «सब जारी करें» दबाता है और पैसा फ्रीलांसर को चला जाता है।' },
  { q: 'प्लेटफ़ॉर्म शुल्क कितना है?',
    a: 'प्लेटफ़ॉर्म फ्रीलांसर के भुगतान में से {fee}% रखता है। उदाहरण: 10π बजट → क्लाइंट 10π देता है, फ्रीलांसर को {net}π मिलते हैं।' },
  { q: 'Pi वॉलेट में भुगतान कैसे मिलेगा?',
    a: 'एस्क्रो जारी होते ही असली Pi आपके Pi Wallet में अपने आप आ जाते हैं। ज़रूरी: आपका Pi वॉलेट बना होना चाहिए और लॉगिन के समय वॉलेट पते तक पहुँच की अनुमति देनी होगी। वॉलेट न हो तो Pi Browser में बनाएँ और Work Pro में दोबारा लॉगिन करें।' },
  { q: '«आवेदन» और «प्रस्ताव» में क्या अंतर है?',
    a: '«आवेदन» वे अनुरोध हैं जो आपने दूसरों के कामों पर भेजे। «प्रस्ताव» वे काम हैं जो क्लाइंट ने सीधे आपको भेजे — इन्हें «मेरे काम → प्रस्ताव» में स्वीकार या अस्वीकार करें।' },
  { q: 'पोर्टफोलियो क्या है?',
    a: 'प्रोफ़ाइल में आपके कामों की प्रदर्शनी। नियुक्ति के समय क्लाइंट इसे देखते हैं, इसलिए अपने बेहतरीन प्रोजेक्ट संक्षिप्त विवरण के साथ जोड़ें।' },
  { q: 'काम पसंद न आए तो क्या करें?',
    a: 'एस्क्रो जारी न करें। एस्क्रो पेज पर «विवाद» खोलें — व्यवस्थापक समीक्षा कर तय करेगा: फ्रीलांसर को भुगतान करना है या आपको वापसी। जब तक काम जमा नहीं हुआ, «रद्द करें» दबाकर पैसा वापस भी ले सकते हैं।' },
  { q: 'अगर क्लाइंट गायब हो जाए और काम स्वीकार न करे?',
    a: 'यदि आपने काम जमा कर दिया और क्लाइंट 14 दिन तक जवाब नहीं देता, तो एस्क्रो अपने आप आपको जारी हो जाता है।' },
  { q: 'क्या भुगतान असली Pi में होता है?',
    a: 'हाँ। Work Pro Pi मेननेट पर चलता है, इसलिए सभी भुगतान असली Pi में होते हैं। काम स्वीकार होने तक राशि एस्क्रो में रहती है।' },
  { q: 'अपना काम कैसे हटाएँ?',
    a: 'खुला काम उसके पेज से हटाया जा सकता है। चल रहा काम नहीं हटता — पहले उसे पूरा करें या एस्क्रो रद्द करें।' },
];

const zh: QA[] = [
  { q: '什么是连接点？为什么需要它？',
    a: '连接点是应用内的活动货币。发布任务消耗 1 个连接点；申请任务按预算每 50π 消耗 1 个（最少 1 个）。申请被拒或任务被删除时，连接点不予退还。可在个人资料页用 Pi 购买。' },
  { q: '托管是怎么运作的？',
    a: '雇用时，客户用 Pi 支付任务预算，资金锁定在托管中。自由职业者可以安心工作，报酬有保障。验收后客户点击「全部放行」，款项即转给自由职业者。' },
  { q: '平台佣金是多少？',
    a: '平台从支付给自由职业者的款项中抽取 {fee}%。例如：预算 10π → 客户支付 10π，自由职业者收到 {net}π。' },
  { q: '如何把钱收到我的 Pi 钱包？',
    a: '托管放行时，真实的 Pi 会自动到账你的 Pi Wallet。注意：你必须已创建 Pi 钱包，并在登录时允许访问钱包地址。若此前没有钱包，请在 Pi Browser 中创建后重新登录 Work Pro。' },
  { q: '「申请」和「邀约」有什么区别？',
    a: '「申请」是你主动投给别人任务的请求。「邀约」是客户直接发给你的任务——可在「我的工作 → 邀约」中接受或拒绝。' },
  { q: '作品集是什么？',
    a: '个人资料中的作品展示。客户挑选人选时会查看，请添加你最好的项目并附简短说明。' },
  { q: '如果对成果不满意怎么办？',
    a: '先不要放行托管。在托管页面发起「争议」，管理员会审核并决定支付给自由职业者还是退款给你。在尚未交付前，你也可以点「取消」直接退款。' },
  { q: '如果客户失联、一直不验收呢？',
    a: '你已交付而客户 14 天没有回应的，托管款项会自动放行给你。' },
  { q: '支付的是真实的 Pi 吗？',
    a: '是的。Work Pro 运行在 Pi 主网上，所有支付都是真实的 Pi。资金由第三方托管，直到工作被验收。' },
  { q: '如何删除我发布的任务？',
    a: '未开始的任务可在任务页面删除。进行中的任务不能删除——请先完成它或取消托管。' },
];

const ja: QA[] = [
  { q: 'コネクトとは何ですか？',
    a: 'コネクトはアプリ内の活動用通貨です。案件の掲載に 1 コネクト、応募には予算 50π ごとに 1 コネクト（最低 1）かかります。応募が却下された場合や案件が削除された場合、コネクトは返却されません。プロフィールから Pi で購入できます。' },
  { q: 'エスクローはどう動きますか？',
    a: '採用時にクライアントが案件予算を Pi で支払い、資金はエスクローに保管されます。フリーランサーは支払いが保証された状態で作業できます。納品物が承認されると、クライアントが「すべて支払う」を押して資金がフリーランサーへ渡ります。' },
  { q: 'プラットフォーム手数料は？',
    a: 'プラットフォームはフリーランサーへの支払いから {fee}% を差し引きます。例：予算 10π → クライアントは 10π を支払い、フリーランサーは {net}π を受け取ります。' },
  { q: 'Pi ウォレットへの入金方法は？',
    a: 'エスクローが解放されると、実際の Pi が自動的に Pi Wallet に届きます。重要：Pi ウォレットを作成済みであること、そしてログイン時にウォレットアドレスへのアクセスを許可することが必要です。ウォレットがない場合は Pi Browser で作成し、Work Pro に入り直してください。' },
  { q: '「応募」と「オファー」の違いは？',
    a: '「応募」はあなたが他人の案件へ送った申し込みです。「オファー」はクライアントがあなたへ直接送った案件で、「マイジョブ → オファー」から承諾・辞退できます。' },
  { q: 'ポートフォリオとは？',
    a: 'プロフィール上の実績展示です。クライアントは採用時にこれを見るので、代表的な案件を短い説明とともに追加してください。' },
  { q: '成果物に納得できない場合は？',
    a: 'エスクローを解放しないでください。エスクローのページで「異議」を申し立てると、管理者が確認してフリーランサーへ支払うか返金するかを判断します。納品前であれば「キャンセル」で返金を受けることもできます。' },
  { q: 'クライアントが消えて検収しない場合は？',
    a: '納品後 14 日間クライアントから反応がない場合、エスクローは自動的にあなたへ支払われます。' },
  { q: '支払いは本物の Pi ですか？',
    a: 'はい。Work Pro は Pi メインネットで動作しており、すべての支払いは本物の Pi です。資金は作業が承認されるまでエスクローで保管されます。' },
  { q: '自分の案件を削除するには？',
    a: '募集中の案件は案件ページから削除できます。進行中の案件は削除できません — 先に完了させるか、エスクローをキャンセルしてください。' },
];

const ko: QA[] = [
  { q: '커넥트란 무엇이고 왜 필요한가요?',
    a: '커넥트는 앱 내 활동 재화입니다. 일자리 등록에 1커넥트, 지원에는 예산 50π당 1커넥트(최소 1)가 듭니다. 지원이 거절되거나 일자리가 삭제돼도 커넥트는 환불되지 않습니다. 프로필에서 Pi로 구매할 수 있습니다.' },
  { q: '에스크로는 어떻게 작동하나요?',
    a: '채용 시 클라이언트가 예산을 Pi로 결제하면 자금이 에스크로에 잠깁니다. 프리랜서는 대금이 보장된 상태로 작업합니다. 결과물이 승인되면 클라이언트가 “전액 지급”을 눌러 자금이 프리랜서에게 전달됩니다.' },
  { q: '플랫폼 수수료는 얼마인가요?',
    a: '플랫폼은 프리랜서 지급액의 {fee}%를 가져갑니다. 예: 예산 10π → 클라이언트는 10π를 결제하고 프리랜서는 {net}π를 받습니다.' },
  { q: 'Pi 지갑으로 어떻게 받나요?',
    a: '에스크로가 해제되면 실제 Pi가 자동으로 Pi Wallet에 입금됩니다. 중요: Pi 지갑이 생성되어 있어야 하고, 로그인 시 지갑 주소 접근을 허용해야 합니다. 지갑이 없었다면 Pi Browser에서 만든 뒤 Work Pro에 다시 로그인하세요.' },
  { q: '“지원”과 “제안”의 차이는?',
    a: '“지원”은 내가 다른 사람의 일자리에 보낸 신청입니다. “제안”은 클라이언트가 나에게 직접 보낸 일자리로, 내 일자리 → 제안에서 수락하거나 거절합니다.' },
  { q: '포트폴리오란?',
    a: '프로필에 있는 작업물 전시입니다. 클라이언트가 채용할 때 확인하므로, 대표 프로젝트를 짧은 설명과 함께 추가하세요.' },
  { q: '결과물이 마음에 들지 않으면?',
    a: '에스크로를 해제하지 마세요. 에스크로 페이지에서 “분쟁”을 열면 관리자가 검토해 프리랜서에게 지급할지 환불할지 결정합니다. 아직 납품 전이라면 “취소”로 환불받을 수도 있습니다.' },
  { q: '클라이언트가 사라져 검수를 안 하면?',
    a: '작업을 제출했는데 클라이언트가 14일간 응답하지 않으면 에스크로가 자동으로 지급됩니다.' },
  { q: '결제는 실제 Pi인가요?',
    a: '네. Work Pro는 Pi 메인넷에서 운영되므로 모든 결제는 실제 Pi입니다. 대금은 작업이 승인될 때까지 에스크로에 보관됩니다.' },
  { q: '등록한 일자리를 삭제하려면?',
    a: '모집 중인 일자리는 해당 페이지에서 삭제할 수 있습니다. 진행 중인 일자리는 삭제할 수 없으니 먼저 완료하거나 에스크로를 취소하세요.' },
];

const vi: QA[] = [
  { q: 'Connect là gì và để làm gì?',
    a: 'Connect là đơn vị hoạt động trong ứng dụng. Đăng một công việc tốn 1 connect; ứng tuyển tốn 1 connect cho mỗi 50π ngân sách (tối thiểu 1). Connect không được hoàn khi hồ sơ bị từ chối hoặc công việc bị xóa. Bạn có thể mua bằng Pi trong hồ sơ cá nhân.' },
  { q: 'Ký quỹ hoạt động thế nào?',
    a: 'Khi thuê, khách hàng trả ngân sách bằng Pi và tiền được khóa trong ký quỹ. Freelancer làm việc với khoản thanh toán đã được bảo đảm. Sau khi nghiệm thu, khách hàng bấm “Giải ngân tất cả” và tiền chuyển cho freelancer.' },
  { q: 'Phí nền tảng là bao nhiêu?',
    a: 'Nền tảng giữ {fee}% từ khoản trả cho freelancer. Ví dụ: ngân sách 10π → khách hàng trả 10π, freelancer nhận {net}π.' },
  { q: 'Nhận tiền về ví Pi bằng cách nào?',
    a: 'Tiền về ví Pi Wallet của bạn dưới dạng Pi thật, tự động khi ký quỹ được giải ngân. Quan trọng: bạn phải đã tạo ví Pi và cho phép truy cập địa chỉ ví khi đăng nhập. Nếu chưa có ví, hãy tạo trong Pi Browser rồi đăng nhập lại Work Pro.' },
  { q: '“Đã ứng tuyển” khác “Lời mời” thế nào?',
    a: '“Đã ứng tuyển” là những hồ sơ BẠN gửi tới công việc của người khác. “Lời mời” là công việc khách hàng gửi thẳng cho BẠN — chấp nhận hoặc từ chối ở Công việc của tôi → Lời mời.' },
  { q: 'Hồ sơ năng lực là gì?',
    a: 'Nơi trưng bày tác phẩm của bạn trên trang cá nhân. Khách hàng xem nó khi chọn người, nên hãy thêm các dự án tốt nhất kèm mô tả ngắn.' },
  { q: 'Nếu tôi không hài lòng với công việc?',
    a: 'Đừng giải ngân ký quỹ. Mở “Tranh chấp” ở trang Ký quỹ, quản trị viên sẽ xem xét và quyết định trả cho freelancer hay hoàn tiền cho bạn. Khi chưa bàn giao, bạn cũng có thể bấm “Hủy” để được hoàn tiền.' },
  { q: 'Nếu khách hàng biến mất và không nghiệm thu?',
    a: 'Nếu bạn đã bàn giao mà khách hàng không phản hồi trong 14 ngày, ký quỹ sẽ tự động giải ngân cho bạn.' },
  { q: 'Thanh toán có phải là Pi thật không?',
    a: 'Có. Work Pro chạy trên Mainnet của Pi nên mọi khoản thanh toán đều là Pi thật. Tiền được giữ trong ký quỹ cho đến khi công việc được chấp nhận.' },
  { q: 'Xóa công việc của tôi thế nào?',
    a: 'Công việc đang mở có thể xóa từ trang của nó. Công việc đang thực hiện thì không — hãy hoàn tất hoặc hủy ký quỹ trước.' },
];

const id: QA[] = [
  { q: 'Apa itu connect dan untuk apa?',
    a: 'Connect adalah mata uang aktivitas di dalam aplikasi. Memasang pekerjaan menghabiskan 1 connect; melamar menghabiskan 1 connect per 50π anggaran (minimal 1). Connect tidak dikembalikan jika lamaran ditolak atau pekerjaan dihapus. Anda bisa membelinya dengan Pi di profil.' },
  { q: 'Bagaimana escrow bekerja?',
    a: 'Saat merekrut, klien membayar anggaran dengan Pi dan dana dikunci di escrow. Freelancer bekerja dengan pembayaran yang terjamin. Setelah pekerjaan diterima, klien menekan “Cairkan semua” dan dana berpindah ke freelancer.' },
  { q: 'Berapa biaya platform?',
    a: 'Platform menahan {fee}% dari pembayaran ke freelancer. Contoh: anggaran 10π → klien membayar 10π, freelancer menerima {net}π.' },
  { q: 'Bagaimana dana masuk ke dompet Pi saya?',
    a: 'Pembayaran masuk sebagai Pi asli ke Pi Wallet Anda secara otomatis saat escrow dicairkan. Penting: Anda harus sudah membuat dompet Pi dan mengizinkan akses ke alamat dompet saat masuk. Jika belum punya, buat di Pi Browser lalu masuk lagi ke Work Pro.' },
  { q: 'Apa beda “Lamaran” dan “Penawaran”?',
    a: '“Lamaran” adalah permohonan yang ANDA kirim ke pekerjaan orang lain. “Penawaran” adalah pekerjaan yang dikirim klien langsung kepada ANDA — terima atau tolak di Pekerjaan Saya → Penawaran.' },
  { q: 'Apa itu portofolio?',
    a: 'Etalase karya Anda di profil. Klien melihatnya saat memilih siapa yang direkrut, jadi tambahkan proyek terbaik dengan deskripsi singkat.' },
  { q: 'Bagaimana jika hasil kerjanya tidak memuaskan?',
    a: 'Jangan cairkan escrow. Buka “Sengketa” di halaman Escrow — admin akan meninjau dan memutuskan membayar freelancer atau mengembalikan dana kepada Anda. Selama belum ada penyerahan, Anda juga bisa menekan “Batal” untuk pengembalian dana.' },
  { q: 'Bagaimana jika klien menghilang dan tidak menerima pekerjaan?',
    a: 'Jika Anda sudah menyerahkan pekerjaan dan klien tidak merespons selama 14 hari, escrow dicairkan ke Anda secara otomatis.' },
  { q: 'Apakah pembayaran memakai Pi asli?',
    a: 'Ya. Work Pro berjalan di Mainnet Pi, jadi semua pembayaran memakai Pi asli. Dana ditahan di escrow sampai pekerjaan diterima.' },
  { q: 'Bagaimana menghapus pekerjaan saya?',
    a: 'Pekerjaan yang masih terbuka bisa dihapus dari halamannya. Pekerjaan yang sedang berjalan tidak bisa — selesaikan dulu atau batalkan escrow.' },
];

const th: QA[] = [
  { q: 'connect คืออะไร และมีไว้ทำไม?',
    a: 'connect คือหน่วยกิจกรรมภายในแอป การลงประกาศงานใช้ 1 connect ส่วนการสมัครใช้ 1 connect ต่อทุก 50π ของงบประมาณ (ขั้นต่ำ 1) หากใบสมัครถูกปฏิเสธหรืองานถูกลบ จะไม่คืน connect ให้ ซื้อได้ด้วย Pi ในหน้าโปรไฟล์' },
  { q: 'เอสโครว์ทำงานอย่างไร?',
    a: 'เมื่อจ้างงาน ลูกค้าจ่ายงบประมาณเป็น Pi และเงินจะถูกล็อกไว้ในเอสโครว์ ฟรีแลนซ์จึงทำงานได้โดยมั่นใจว่าจะได้เงิน เมื่อรับงานแล้ว ลูกค้ากด «จ่ายทั้งหมด» เงินก็จะไปถึงฟรีแลนซ์' },
  { q: 'ค่าธรรมเนียมแพลตฟอร์มเท่าไร?',
    a: 'แพลตฟอร์มหัก {fee}% จากยอดที่จ่ายให้ฟรีแลนซ์ ตัวอย่าง: งบ 10π → ลูกค้าจ่าย 10π ฟรีแลนซ์ได้รับ {net}π' },
  { q: 'รับเงินเข้ากระเป๋า Pi อย่างไร?',
    a: 'เงินจะเข้ากระเป๋า Pi Wallet ของคุณเป็น Pi จริงโดยอัตโนมัติเมื่อเอสโครว์ถูกปล่อย สำคัญ: คุณต้องสร้างกระเป๋า Pi ไว้แล้ว และต้องอนุญาตการเข้าถึงที่อยู่กระเป๋าตอนเข้าสู่ระบบ หากยังไม่มี ให้สร้างใน Pi Browser แล้วเข้า Work Pro ใหม่' },
  { q: '«ที่สมัคร» ต่างจาก «ข้อเสนอ» อย่างไร?',
    a: '«ที่สมัคร» คือใบสมัครที่คุณส่งไปยังงานของคนอื่น ส่วน «ข้อเสนอ» คืองานที่ลูกค้าส่งมาหาคุณโดยตรง — ตอบรับหรือปฏิเสธได้ที่ งานของฉัน → ข้อเสนอ' },
  { q: 'ผลงาน (portfolio) คืออะไร?',
    a: 'พื้นที่แสดงผลงานของคุณในโปรไฟล์ ลูกค้าจะดูตอนเลือกคนทำงาน ให้ใส่โปรเจกต์ที่ดีที่สุดพร้อมคำอธิบายสั้น ๆ' },
  { q: 'ถ้าไม่พอใจผลงานต้องทำอย่างไร?',
    a: 'อย่าเพิ่งปล่อยเอสโครว์ เปิด «ข้อพิพาท» ในหน้าเอสโครว์ ผู้ดูแลจะตรวจสอบและตัดสินว่าจะจ่ายให้ฟรีแลนซ์หรือคืนเงินให้คุณ ระหว่างที่ยังไม่ส่งงาน คุณกด «ยกเลิก» เพื่อรับเงินคืนได้เช่นกัน' },
  { q: 'ถ้าลูกค้าหายไปและไม่รับงาน?',
    a: 'ถ้าคุณส่งงานแล้วและลูกค้าไม่ตอบภายใน 14 วัน เอสโครว์จะถูกปล่อยให้คุณโดยอัตโนมัติ' },
  { q: 'การชำระเงินเป็น Pi จริงหรือไม่?',
    a: 'ใช่ Work Pro ทำงานบนเมนเน็ตของ Pi การชำระเงินทั้งหมดจึงเป็น Pi จริง เงินจะถูกพักไว้ในเอสโครว์จนกว่างานจะได้รับการยอมรับ' },
  { q: 'ลบงานของตัวเองอย่างไร?',
    a: 'งานที่ยังเปิดอยู่ลบได้จากหน้างานนั้น ส่วนงานที่กำลังดำเนินการลบไม่ได้ — ต้องปิดงานหรือยกเลิกเอสโครว์ก่อน' },
];

const tl: QA[] = [
  { q: 'Ano ang connects at bakit kailangan?',
    a: 'Ang connects ang panloob na pera para sa aktibidad. Ang pag-post ng trabaho ay 1 connect; ang pag-apply ay 1 connect kada 50π ng budget (minimum 1). Hindi ibinabalik ang connects kapag tinanggihan ang aplikasyon o binura ang trabaho. Mabibili ang mga ito gamit ang Pi sa profile.' },
  { q: 'Paano gumagana ang escrow?',
    a: 'Kapag kumuha ng freelancer, binabayaran ng kliyente ang budget sa Pi at nakakandado ito sa escrow. Panatag ang freelancer dahil sigurado ang bayad. Pagkatapos tanggapin ang trabaho, pipindutin ng kliyente ang “Cairkan lahat” at mapupunta ang pera sa freelancer.' },
  { q: 'Magkano ang bayad ng platform?',
    a: 'Kinukuha ng platform ang {fee}% ng bayad sa freelancer. Halimbawa: 10π na budget → nagbabayad ang kliyente ng 10π at tumatanggap ang freelancer ng {net}π.' },
  { q: 'Paano ako babayaran sa Pi wallet ko?',
    a: 'Awtomatikong dumarating ang totoong Pi sa iyong Pi Wallet kapag inilabas ang escrow. Mahalaga: kailangang may nagawa ka nang Pi wallet at payagan ang access sa address nito kapag nag-sign in. Kung wala pa, gumawa sa Pi Browser at mag-sign in ulit sa Work Pro.' },
  { q: 'Ano ang pagkakaiba ng “Inaplayan” at “Mga alok”?',
    a: 'Ang “Inaplayan” ay mga aplikasyong IKAW ang nagpadala sa trabaho ng iba. Ang “Mga alok” ay trabahong direktang ipinadala sa IYO ng kliyente — tanggapin o tanggihan sa Mga trabaho ko → Mga alok.' },
  { q: 'Ano ang portfolio?',
    a: 'Ito ang tanghalan ng iyong mga gawa sa profile. Tinitingnan ito ng kliyente kapag pumipili kung sino ang kukunin, kaya idagdag ang pinakamahusay mong proyekto na may maikling paglalarawan.' },
  { q: 'Paano kung hindi maganda ang trabaho?',
    a: 'Huwag ilabas ang escrow. Magbukas ng “Sigalot” sa pahina ng Escrow — susuriin ito ng administrador at magpapasya kung babayaran ang freelancer o isasauli sa iyo. Habang wala pang naisusumite, puwede ring pindutin ang “Kanselahin” para sa refund.' },
  { q: 'Paano kung nawala ang kliyente at hindi tinanggap ang trabaho?',
    a: 'Kung naisumite mo na ang trabaho at hindi tumugon ang kliyente sa loob ng 14 araw, awtomatikong ilalabas sa iyo ang escrow.' },
  { q: 'Totoong Pi ba ang mga bayad?',
    a: 'Oo. Tumatakbo ang Work Pro sa Mainnet ng Pi, kaya totoong Pi ang lahat ng bayad. Nakalagak ang pera sa escrow hanggang tanggapin ang trabaho.' },
  { q: 'Paano burahin ang trabaho ko?',
    a: 'Ang bukas na trabaho ay puwedeng burahin mula sa pahina nito. Ang trabahong isinasagawa ay hindi — tapusin muna ito o kanselahin ang escrow.' },
];

const nl: QA[] = [
  { q: 'Wat zijn connects en waarvoor dienen ze?',
    a: 'Connects zijn de interne activiteitsmunt. Een opdracht plaatsen kost 1 connect; solliciteren kost 1 connect per 50π budget (minimaal 1). Connects worden niet terugbetaald als je sollicitatie wordt afgewezen of de opdracht wordt verwijderd. Je koopt ze met Pi in je profiel.' },
  { q: 'Hoe werkt escrow?',
    a: 'Bij het aannemen betaalt de klant het budget in Pi en wordt het geld vastgezet in escrow. De freelancer werkt met gegarandeerde betaling. Na goedkeuring tikt de klant op “Alles vrijgeven” en gaat het geld naar de freelancer.' },
  { q: 'Wat is de platformkosten?',
    a: 'Het platform houdt {fee}% in van de uitbetaling aan de freelancer. Voorbeeld: budget van 10π → de klant betaalt 10π en de freelancer ontvangt {net}π.' },
  { q: 'Hoe word ik uitbetaald op mijn Pi-wallet?',
    a: 'Uitbetalingen komen automatisch als echte Pi in je Pi Wallet zodra de escrow wordt vrijgegeven. Belangrijk: je moet een Pi-wallet hebben aangemaakt en bij het inloggen toegang tot het walletadres toestaan. Had je er geen, maak er dan een in Pi Browser en log opnieuw in bij Work Pro.' },
  { q: 'Wat is het verschil tussen “Gesolliciteerd” en “Aanbiedingen”?',
    a: '“Gesolliciteerd” zijn de aanvragen die JIJ naar andermans opdrachten stuurde. “Aanbiedingen” zijn opdrachten die een klant rechtstreeks naar JOU stuurde — accepteer of weiger ze bij Mijn opdrachten → Aanbiedingen.' },
  { q: 'Wat is het portfolio?',
    a: 'Een etalage van je werk op je profiel. Klanten bekijken het bij het kiezen van een freelancer, dus voeg je beste projecten toe met een korte beschrijving.' },
  { q: 'Wat als het werk niet bevalt?',
    a: 'Geef de escrow niet vrij. Open een “Geschil” op de Escrow-pagina; een beheerder beoordeelt het en beslist of de freelancer wordt betaald of jij wordt terugbetaald. Zolang er niets is opgeleverd, kun je ook op “Annuleren” tikken voor terugbetaling.' },
  { q: 'Wat als de klant verdwijnt en het werk nooit accepteert?',
    a: 'Heb je het werk opgeleverd en reageert de klant 14 dagen niet, dan wordt de escrow automatisch aan jou uitbetaald.' },
  { q: 'Zijn de betalingen echte Pi?',
    a: 'Ja. Work Pro draait op het Pi-mainnet, dus alle betalingen zijn echte Pi. Het geld blijft in escrow tot het werk is geaccepteerd.' },
  { q: 'Hoe verwijder ik mijn opdracht?',
    a: 'Een open opdracht verwijder je vanaf de opdrachtpagina. Een lopende opdracht niet — rond die eerst af of annuleer de escrow.' },
];

const sv: QA[] = [
  { q: 'Vad är connects och varför behövs de?',
    a: 'Connects är appens interna aktivitetsvaluta. Att lägga upp ett uppdrag kostar 1 connect; att ansöka kostar 1 connect per 50π budget (minst 1). Connects återbetalas inte om din ansökan avslås eller uppdraget raderas. Du köper dem med Pi i profilen.' },
  { q: 'Hur fungerar escrow?',
    a: 'Vid anlitande betalar kunden budgeten i Pi och pengarna låses i escrow. Frilansaren arbetar med betalningen säkrad. När arbetet godkänts trycker kunden på ”Betala ut allt” och pengarna går till frilansaren.' },
  { q: 'Hur stor är plattformsavgiften?',
    a: 'Plattformen behåller {fee}% av utbetalningen till frilansaren. Exempel: budget på 10π → kunden betalar 10π och frilansaren får {net}π.' },
  { q: 'Hur får jag betalt till min Pi-plånbok?',
    a: 'Utbetalningar kommer som riktiga Pi till din Pi Wallet automatiskt när escrow frisläpps. Viktigt: du måste ha skapat en Pi-plånbok och tillåta åtkomst till plånboksadressen vid inloggning. Saknar du plånbok, skapa en i Pi Browser och logga in i Work Pro igen.' },
  { q: 'Vad skiljer ”Ansökta” från ”Erbjudanden”?',
    a: '”Ansökta” är ansökningar som DU skickat till andras uppdrag. ”Erbjudanden” är uppdrag som en kund skickat direkt till DIG — acceptera eller avböj under Mina uppdrag → Erbjudanden.' },
  { q: 'Vad är portfolion?',
    a: 'Ett skyltfönster för dina arbeten på profilen. Kunder tittar på den när de väljer vem de ska anlita, så lägg till dina bästa projekt med en kort beskrivning.' },
  { q: 'Vad gör jag om arbetet inte duger?',
    a: 'Frisläpp inte escrow. Öppna en ”Tvist” på Escrow-sidan så granskar en administratör och avgör om frilansaren ska få betalt eller om du ska få pengarna tillbaka. Så länge inget levererats kan du också trycka ”Avbryt” för återbetalning.' },
  { q: 'Vad händer om kunden försvinner och aldrig godkänner?',
    a: 'Har du levererat och kunden inte svarar på 14 dagar betalas escrow ut till dig automatiskt.' },
  { q: 'Är betalningarna riktiga Pi?',
    a: 'Ja. Work Pro körs på Pis mainnet, så alla betalningar är riktiga Pi. Pengarna hålls i escrow tills arbetet har godkänts.' },
  { q: 'Hur raderar jag mitt uppdrag?',
    a: 'Ett öppet uppdrag raderas från uppdragssidan. Ett pågående går inte att radera — slutför det eller avbryt escrow först.' },
];

const ro: QA[] = [
  { q: 'Ce sunt connecturile și la ce folosesc?',
    a: 'Connecturile sunt moneda internă de activitate. Publicarea unui proiect costă 1 connect, iar candidatura costă 1 connect pentru fiecare 50π din buget (minimum 1). Connecturile nu se restituie dacă îți este respinsă candidatura sau proiectul este șters. Le poți cumpăra cu Pi din profil.' },
  { q: 'Cum funcționează escrow-ul?',
    a: 'La angajare, clientul plătește bugetul în Pi, iar banii sunt blocați în escrow. Freelancerul lucrează cu plata asigurată. După acceptarea lucrării, clientul apasă „Eliberează tot” și banii ajung la freelancer.' },
  { q: 'Cât este comisionul platformei?',
    a: 'Platforma reține {fee}% din plata către freelancer. Exemplu: buget de 10π → clientul plătește 10π, iar freelancerul primește {net}π.' },
  { q: 'Cum primesc banii în portofelul Pi?',
    a: 'Plățile ajung ca Pi reali în Pi Wallet automat la eliberarea escrow-ului. Important: trebuie să ai un portofel Pi creat și să permiți accesul la adresa lui la autentificare. Dacă nu aveai portofel, creează unul în Pi Browser și intră din nou în Work Pro.' },
  { q: 'Care e diferența dintre „Candidaturi” și „Oferte”?',
    a: '„Candidaturile” sunt cererile pe care TU le-ai trimis la proiectele altora. „Ofertele” sunt proiecte trimise de un client direct ȚIE — le accepți sau refuzi în Proiectele mele → Oferte.' },
  { q: 'Ce este portofoliul?',
    a: 'O vitrină a lucrărilor tale din profil. Clienții o consultă când aleg pe cine angajează, așa că adaugă cele mai bune proiecte cu o descriere scurtă.' },
  { q: 'Ce fac dacă lucrarea nu îmi convine?',
    a: 'Nu elibera escrow-ul. Deschide un „Litigiu” în pagina Escrow — un administrator va analiza și va decide dacă se plătește freelancerul sau ți se restituie banii. Cât timp nu s-a predat nimic, poți apăsa și „Anulează” pentru rambursare.' },
  { q: 'Ce se întâmplă dacă clientul dispare și nu acceptă lucrarea?',
    a: 'Dacă ai predat lucrarea și clientul nu răspunde 14 zile, escrow-ul îți este eliberat automat.' },
  { q: 'Plățile sunt în Pi reali?',
    a: 'Da. Work Pro rulează pe Mainnet-ul Pi, deci toate plățile sunt în Pi reali. Fondurile rămân în escrow până când lucrarea este acceptată.' },
  { q: 'Cum îmi șterg proiectul?',
    a: 'Un proiect deschis se poate șterge din pagina lui. Unul în derulare nu — finalizează-l sau anulează mai întâi escrow-ul.' },
];

const bn: QA[] = [
  { q: 'কানেক্ট কী এবং কেন দরকার?',
    a: 'কানেক্ট হলো অ্যাপের অভ্যন্তরীণ কার্যক্রম-মুদ্রা। কাজ পোস্ট করতে ১টি কানেক্ট লাগে; আবেদন করতে বাজেটের প্রতি ৫০π-এর জন্য ১টি (ন্যূনতম ১)। আবেদন প্রত্যাখ্যাত হলে বা কাজ মুছে গেলে কানেক্ট ফেরত দেওয়া হয় না। প্রোফাইল থেকে Pi দিয়ে কিনতে পারেন।' },
  { q: 'এসক্রো কীভাবে কাজ করে?',
    a: 'নিয়োগের সময় ক্লায়েন্ট বাজেট Pi-তে পরিশোধ করেন এবং অর্থ এসক্রোতে আটকে থাকে। ফ্রিল্যান্সার নিশ্চিন্তে কাজ করেন — পেমেন্ট নিশ্চিত। কাজ গৃহীত হলে ক্লায়েন্ট «সব জারি করুন» চাপলে টাকা ফ্রিল্যান্সারের কাছে যায়।' },
  { q: 'প্ল্যাটফর্ম ফি কত?',
    a: 'প্ল্যাটফর্ম ফ্রিল্যান্সারের প্রাপ্য থেকে {fee}% রাখে। উদাহরণ: ১০π বাজেট → ক্লায়েন্ট ১০π দেন, ফ্রিল্যান্সার পান {net}π।' },
  { q: 'Pi ওয়ালেটে টাকা কীভাবে পাব?',
    a: 'এসক্রো ছাড়ার সঙ্গে সঙ্গে আসল Pi স্বয়ংক্রিয়ভাবে আপনার Pi Wallet-এ পৌঁছায়। গুরুত্বপূর্ণ: আপনার Pi ওয়ালেট তৈরি থাকতে হবে এবং লগইনের সময় ওয়ালেট ঠিকানায় অ্যাক্সেস অনুমোদন করতে হবে। ওয়ালেট না থাকলে Pi Browser-এ তৈরি করে আবার Work Pro-তে ঢুকুন।' },
  { q: '«আবেদন» আর «প্রস্তাব»-এর পার্থক্য কী?',
    a: '«আবেদন» হলো আপনি অন্যের কাজে যেসব অনুরোধ পাঠিয়েছেন। «প্রস্তাব» হলো ক্লায়েন্ট সরাসরি আপনাকে যে কাজ পাঠিয়েছেন — «আমার কাজ → প্রস্তাব» থেকে গ্রহণ বা প্রত্যাখ্যান করুন।' },
  { q: 'পোর্টফোলিও কী?',
    a: 'প্রোফাইলে আপনার কাজের প্রদর্শনী। কাকে নিয়োগ দেবেন তা বাছাইয়ের সময় ক্লায়েন্টরা এটি দেখেন, তাই সেরা প্রজেক্টগুলো সংক্ষিপ্ত বিবরণসহ যোগ করুন।' },
  { q: 'কাজ পছন্দ না হলে কী করব?',
    a: 'এসক্রো ছাড়বেন না। এসক্রো পাতায় «বিরোধ» খুলুন — প্রশাসক পর্যালোচনা করে ঠিক করবেন ফ্রিল্যান্সারকে দেওয়া হবে না আপনাকে ফেরত। কাজ জমা না হওয়া পর্যন্ত «বাতিল» চেপে টাকা ফেরতও নিতে পারেন।' },
  { q: 'ক্লায়েন্ট উধাও হয়ে কাজ গ্রহণ না করলে?',
    a: 'আপনি কাজ জমা দেওয়ার পর ক্লায়েন্ট ১৪ দিন সাড়া না দিলে এসক্রো স্বয়ংক্রিয়ভাবে আপনাকে দেওয়া হয়।' },
  { q: 'পেমেন্ট কি আসল Pi-তে হয়?',
    a: 'হ্যাঁ। Work Pro Pi মেইননেটে চলে, তাই সব পেমেন্ট আসল Pi-তে হয়। কাজ গৃহীত না হওয়া পর্যন্ত অর্থ এসক্রোতে থাকে।' },
  { q: 'নিজের কাজ কীভাবে মুছব?',
    a: 'খোলা কাজ তার পাতা থেকে মুছে ফেলা যায়। চলমান কাজ মোছা যায় না — আগে সেটি শেষ করুন বা এসক্রো বাতিল করুন।' },
];

export const FAQ_BY_LANG: Record<string, QA[]> = {
  en, ru, uk, de, fr, es, pt, it, tr: tr_, pl, ar, hi, zh, ja, ko,
  vi, id, th, tl, nl, sv, ro, bn,
};

/** FAQ for a language, falling back to English for anything not translated yet. */
export function faqFor(lang: string): QA[] {
  return FAQ_BY_LANG[lang] || FAQ_BY_LANG.en;
}
